name: Auto Book Tee Time

on:
  schedule:
    # Every Monday at 04:01 UTC = 00:01 AM Eastern (approx 10s after midnight local)
    - cron: '1 4 * * 1'
  workflow_dispatch:  # allow manual run

jobs:
  book:
    runs-on: ubuntu-latest

    env:
      CHRONO_EMAIL: ${{ secrets.CHRONO_EMAIL }}
      CHRONO_PWD: ${{ secrets.CHRONO_PWD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium

      - name: Install Chrome & Chromedriver
        uses: nanasess/setup-chromedriver@v2

      - name: Wait 10 seconds for tee times to open
        run: sleep 10

      - name: Run booking script
        run: python autobook.py

      - name: Upload debug artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: debug-artifacts
          path: |
            tee_times_page_source.html
            page_after_load.png
            error_screenshot.png
